package com.nek12.androidutils.room

import androidx.room.CoroutinesRoom
import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Embedded
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.RawQuery
import androidx.room.RoomDatabase
import androidx.room.Update
import androidx.sqlite.db.SimpleSQLiteQuery
import androidx.sqlite.db.SupportSQLiteQuery
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.distinctUntilChanged

/**
 * A generic dao class that provides CRUD methods for you for free.
 * Extend this class to add your own methods.
 * Provides insert, update, delete, and get queries for you.
 * @param db Just add this parameter to your DAO and pass it along to the RoomDao base constructor.
 *   This parameter is an implementation detail and is handled by Room codegen.
 *   example
 *   ```
 *   abstract class MyDao(db: RoomDatabase) : RoomDao<MyEntity>(db, MyEntity.TABLE_NAME)
 *   ```
 * @param referencedTables A list of tables that your [T] entity references. For example, [Embedded] entities.
 *   This is used in `get(): Flow<T>` queries to trigger flow emission when any of the [referencedTables] changes.
 *   By default, emissions are triggered when just the [tableName] table changes
 * @see RoomEntity
 * @see RoomDataSource
 **/
@Dao
abstract class RoomDao<I: Any, T: RoomEntity<I>>(
    private val db: RoomDatabase,
    private val tableName: String,
    private val referencedTables: Array<String> = arrayOf(tableName),
) {

    /**
     * Add or replace an entity
     * @return The rowId of a newly-inserted entity (id if you use autogenerated numeric values for PKs, internal id otherwise)
     */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    abstract suspend fun add(entity: T): Long

    /**
     * Add or replace [entities]
     * returning List of row ids is not supported by google https://issuetracker.google.com/issues/160258066?hl=pt-pt
     */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    abstract suspend fun add(vararg entities: T)

    /**
     * Add or replace [entities]
     *  returning List of row ids is not supported by google https://issuetracker.google.com/issues/160258066?hl=pt-pt
     */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    abstract suspend fun add(entities: List<T>)

    /**
     * @return The number of items that were updated
     */
    @Update
    abstract suspend fun update(entity: T): Int

    /**
     * @return The number of items that were updated
     */
    @Update
    abstract suspend fun update(entities: List<T>): Int

    /**
     * @return The number of items that were updated
     */
    @Update
    abstract suspend fun update(vararg entities: T): Int

    /**
     * @return The number of items that were deleted
     */
    @Delete
    abstract suspend fun delete(entity: T): Int

    /**
     * @return The number of items that were deleted
     */
    @Delete
    abstract suspend fun delete(vararg entity: T): Int

    /**
     * @return The number of items that were deleted
     */
    @Delete
    abstract suspend fun delete(entities: List<T>): Int

    /**
     * @return The number of items that were deleted
     */
    @JvmName("deleteById")
    suspend fun delete(ids: List<I>): Int {
        val idsQuery = buildSqlIdList(ids)
        val query = SimpleSQLiteQuery("DELETE FROM `$tableName` WHERE `id` IN ($idsQuery);")
        return delete(query)
    }

    /**
     * @return The number of items that were deleted
     */
    suspend fun delete(vararg ids: I): Int {
        return delete(ids.toList())
    }

    /**
     * @return The number of items that were deleted
     */
    suspend fun deleteAll(): Int {
        val query = SimpleSQLiteQuery("DELETE FROM `$tableName`;")
        return delete(query)
    }

    /**
     * Get an entity synchronously
     * @return null if no value found
     */
    suspend fun getSync(id: I): T? {
        return getSync(listOf(id)).firstOrNull()
    }

    /**
     * Get entities synchronously
     * @return empty list if no values found
     */
    suspend fun getSync(vararg ids: I): List<T> {
        return getSync(ids.toList())
    }

    /**
     * Get entities synchronously
     * @return empty list if no values found
     */
    suspend fun getAllSync(): List<T> {
        val query = SimpleSQLiteQuery("SELECT * FROM `$tableName`;")
        return getSync(query) ?: emptyList()
    }

    /**
     * Get entities synchronously
     * @return empty list if no values found
     */
    suspend fun getSync(ids: List<I>): List<T> {
        return getSync(buildSqlIdQuery(ids)) ?: emptyList()
    }

    /**
     * Use [Flow.distinctUntilChanged] to prevent duplicate emissions when unrelated entities are changed
     * Re-emits values when any of the [referencedTables] change
     */
    fun get(id: I): Flow<T?> = CoroutinesRoom.createFlow(db, true, referencedTables) {
        getBlocking(buildSqlIdQuery(listOf(id)))?.firstOrNull()
    }

    /**
     * Use [Flow.distinctUntilChanged] to prevent duplicate emissions when unrelated entities are changed
     * Re-emits values when any of the [referencedTables] change
     */
    fun get(vararg ids: I): Flow<List<T>> {
        return get(ids.toList())
    }

    /**
     * Use [Flow.distinctUntilChanged] to prevent duplicate emissions when unrelated entities are changed
     * Re-emits values when any of the [referencedTables] change
     */
    fun get(ids: List<I>): Flow<List<T>> = CoroutinesRoom.createFlow(db, true, referencedTables) {
        getBlocking(buildSqlIdQuery(ids)) ?: emptyList()
    }

    /**
     * Use [Flow.distinctUntilChanged] to prevent duplicate emissions when unrelated entities are changed.
     * Re-emits values when any of the [referencedTables] change
     */
    fun getAll(): Flow<List<T>> {
        return CoroutinesRoom.createFlow(db, true, referencedTables) {
            getBlocking(SimpleSQLiteQuery("SELECT * FROM `$tableName`;")) ?: emptyList()
        }
    }

    @RawQuery
    protected abstract suspend fun delete(query: SupportSQLiteQuery): Int

    @RawQuery
    protected abstract suspend fun getSync(query: SupportSQLiteQuery): List<T>?

    @RawQuery
    protected abstract fun getBlocking(query: SupportSQLiteQuery): List<T>?

    private fun buildSqlIdList(ids: List<I>): String {
        return buildString {
            ids.forEachIndexed { i, id ->
                if (i != 0) {
                    append(",")
                }
                append("'$id'")
            }
        }
    }

    private fun buildSqlIdQuery(ids: List<I>): SimpleSQLiteQuery {
        val idsQ = buildSqlIdList(ids)
        return SimpleSQLiteQuery("SELECT * FROM $tableName WHERE `id` IN ($idsQ);")
    }
}
//
// private fun UUID.toByteBlob(): ByteArray {
//     val bb: ByteBuffer = ByteBuffer.wrap(ByteArray(16))
//     bb.putLong(mostSignificantBits)
//     bb.putLong(leastSignificantBits)
//     return bb.array()
// }
//
// private fun ByteArray.toUUID(): UUID {
//     val bb: ByteBuffer = ByteBuffer.wrap(this)
//     val mostSignificantBits = bb.long
//     val leastSignificantBits = bb.long
//     return UUID(mostSignificantBits, leastSignificantBits)
// }
